### ISSUE TITLE
Illogical calculation.!?

### ISSUE THREAD

**Issue by vladakru** [danpeig/ESP32EnergyMonitor#3]
![Screenshot_20230325-145224](https://user-images.githubusercontent.com/49612100/227724324-2c253369-0a38-4e8c-805c-8403eae96980.png)
what bothers me is that the total current is 4.7A and the total real power is only 362w. is that formula for calculating power a bit messy, I think that with 4A current the real power should be at least 1000w.
the code has not been modified, it is original as you wrote it.

**Comment by danpeig** [comment]
Real power takes into consideration the power factor. This is what is impacting your calculation.

**Comment by danpeig** [comment]
Try inverting the direction of the CT clamps.
