### ISSUE TITLE
Not LOGS 

### ISSUE THREAD

**Issue by juanpablo132** [danpeig/ESP32EnergyMonitor#4]
Hi! I have this problem I trying to LOGS!

_INFO Reading configuration /config/esphome/esp32emon.yaml...
INFO Detected timezone 'America/Argentina/Buenos_Aires'
INFO Starting log output from esp32emon.local using esphome API
WARNING Can't connect to ESPHome API for esp32emon.local: Error connecting to ('192.168.3.131', 6053): [Errno 111] Connect call failed ('192.168.3.131', 6053)
INFO Trying to reconnect to esp32emon.local in the background_

**Comment by danpeig** [comment]
Double check the ESP32 Wifi settings and flash the firmware again using the USB cable.

**Comment by danpeig** [comment]
This is not a ESP32EnergyMonitor issue.
