### ISSUE TITLE
Is the offset of 2.5V not an issue

### ISSUE THREAD

**Issue by paulca99** [danpeig/ESP32EnergyMonitor#5]
Hi Dan , Great readme, I'm about to build this, I've been running on an arduino mega for years. I was just wondering if you'd tried using 3.3V as the Vcc onto the zmpt101b to get the voltage centred correctly around 1.666V , or doesn't it really matter ? it seems to use an LM358 which has a min Vcc of 3V so it might work even though the datasheet for the zmpt101b says 5-30V . Just seems a shame to lose such a big chunk of the ADC resolution.

**Comment by danpeig** [comment]
During my research I found that the module would provide more consistent results if using 5V supply and found that it worked well. Never tried the 3.3V option.

https://surtrtech.com/2020/04/08/measure-any-ac-voltage-250vac-with-zmpt101b-and-esp8266-12e-with-android-app-adafruit-io-mqtt/

**Comment by paulca99** [comment]
Interesting, he's using 3.3V in that example and it seems to work ok.  It's a bit confusing as the write up says "the signal will be lost at some points using 3.3V"  but I think he's just talking about the clipping , which can be cancelled out with the pot. I'll try both.

**Comment by danpeig** [comment]
This user proposed an interesting solution but requires hardware modifications: https://github.com/a-boudersa/ZMPT101B-3.3V-ADC
