### ISSUE TITLE
Warning "ADC_BITS"

### ISSUE THREAD

**Issue by wanball** [danpeig/ESP32EnergyMonitor#7]
I encountered this problem. I don't know if there is a solution or not.
![image](https://github.com/danpeig/ESP32EnergyMonitor/assets/13687974/4759cf30-dbe1-421d-9adc-cdbe9f7d7b29)

**Comment by danpeig** [comment]
This happens because I wanted to keep the original Emon library that was initially written for the ESP8266. The ADC resolution was updated just by declaring the constant again, thus the warning. 

It will not affect the program execution.
